/**
 * GP-143: the studio's download — the generated project as a zip, built
 * client-side from session files (no server round trip, nothing stored),
 * plus a generated README so the unzipped folder explains itself.
 */
import JSZip from "jszip";

import type { StudioFile } from "@/api/types";

/** The zip's README — a static template, deliberately free of any AI claim
 * of correctness: review before you apply is the whole point. */
export function studioReadme(files: StudioFile[]): string {
  const list = files.map((f) => `- \`${f.path}\``).join("\n");
  return `# Terraform project — generated by Groundplan AI Studio

This project was generated from a conversation. **Review it before applying**:
it is a starting point produced by an AI, not a reviewed change.

## Files

${list}

## Requirements

- Terraform >= 1.5
- The \`azurerm\` provider (declared in the project)
- An authenticated Azure context (\`az login\`, or service-principal env vars)

## Usage

\`\`\`sh
terraform init
terraform plan
# review the plan, then
terraform apply
\`\`\`
`;
}

/** The exact file set shown in the studio, plus the README, as a zip Blob. */
export async function buildStudioZip(files: StudioFile[]): Promise<Blob> {
  const zip = new JSZip();
  for (const file of files) {
    zip.file(file.path, file.content);
  }
  zip.file("README.md", studioReadme(files));
  return zip.generateAsync({ type: "blob" });
}
