import type { StarlightUserConfig } from "@astrojs/starlight/types";

/**
 * The information architecture, declared in one place (GP-213/GP-214).
 *
 * Two journeys, in the order a reader meets them: understand what this is, try
 * it, install it, feed it, use it. Every group is a question somebody arrives
 * with — never an internal boundary (there is no "backend" section, because
 * nobody wakes up wanting the backend).
 *
 * Groups are explicit rather than autogenerated: the order of pages inside a
 * group is an editorial decision (read a review before you learn to annotate
 * one), and a directory listing would sort it alphabetically instead. A page
 * lands here in the same commit it is written — `site.test.ts` fails both ways,
 * on a link with no page and on a page in no group.
 */
export const SIDEBAR: StarlightUserConfig["sidebar"] = [
  {
    label: "Get started",
    items: [{ label: "Welcome", link: "/" }],
  },
];
