import type { StarlightUserConfig } from "@astrojs/starlight/types";

/**
 * The information architecture, declared in one place (GP-213/GP-214).
 *
 * Two journeys, in the order a reader meets them: understand what this is, try
 * it, install it, feed it, use it. Every group is a question somebody arrives
 * with — never an internal boundary (there is no "backend" section, because
 * nobody wakes up wanting the backend).
 *
 * Groups are explicit rather than autogenerated: the order of pages inside a
 * group is an editorial decision (read a review before you learn to annotate
 * one), and a directory listing would sort it alphabetically instead. A page
 * lands here in the same commit it is written — `site.test.ts` fails both ways,
 * on a link with no page and on a page in no group.
 */
export const SIDEBAR: StarlightUserConfig["sidebar"] = [
  {
    label: "Get started",
    items: [
      { label: "Welcome", link: "/" },
      { label: "Concepts", link: "/concepts/" },
      { label: "Quickstart", link: "/quickstart/" },
    ],
  },
  {
    label: "Install",
    items: [
      { label: "Docker Compose", link: "/install/docker-compose/" },
      { label: "Kubernetes (Helm)", link: "/install/kubernetes/" },
      { label: "Helm values", link: "/install/helm-values/" },
    ],
  },
  {
    label: "Connect your pipeline",
    items: [
      { label: "CI integration", link: "/ci/" },
      { label: "CLI reference", link: "/ci/cli/" },
      { label: "Kubernetes manifests", link: "/ci/kubernetes/" },
    ],
  },
  {
    label: "Use it",
    items: [
      { label: "Review a pull request", link: "/use/pull-requests/" },
      { label: "Living documentation", link: "/use/living-documentation/" },
      { label: "Lenses", link: "/use/lenses/" },
      { label: "Annotations", link: "/use/annotations/" },
      { label: "Policies", link: "/use/policies/" },
      { label: "Drift & reality", link: "/use/drift-and-reality/" },
      { label: "Exports & sharing", link: "/use/exports/" },
      { label: "Live clusters", link: "/use/live-clusters/" },
      { label: "Playground", link: "/use/playground/" },
      { label: "VS Code extension", link: "/use/vscode/" },
    ],
  },
  {
    label: "AI (optional)",
    items: [
      { label: "The AI layer", link: "/ai/" },
      { label: "AI Studio", link: "/ai/studio/" },
    ],
  },
  {
    label: "Administration",
    items: [
      { label: "Organizations & roles", link: "/admin/organizations/" },
      { label: "Integrations", link: "/admin/integrations/" },
      { label: "Security posture", link: "/admin/security/" },
    ],
  },
  {
    label: "Reference",
    items: [
      { label: "Configuration", link: "/reference/configuration/" },
      { label: "OIDC & single sign-on", link: "/reference/oidc/" },
      { label: "The encryption key", link: "/reference/encryption-key/" },
    ],
  },
  {
    label: "Help",
    items: [
      { label: "Troubleshooting", link: "/help/troubleshooting/" },
      { label: "Known limits", link: "/help/limits/" },
      { label: "FAQ", link: "/help/faq/" },
    ],
  },
];
