import type { FastifyInstance, FastifyPluginAsync } from "fastify";
import { and, desc, eq, isNull } from "drizzle-orm";

import {
  graphSnapshots,
  ingestionEvents,
  publicEventColumns,
  pullRequests,
  repositories,
  type RepositoryRow,
} from "../db/schema.js";
import { changesFromBase } from "../graph/change-diff.js";
import { mapK8sObjects, type K8sObject } from "../graph/k8s-mapper.js";
import { InvalidManifestError, parseManifestStream } from "../graph/manifest-parser.js";
import { isTerraformPlan, parsePlanToGraph } from "../graph/plan-parser.js";
import { insertGraphSnapshot } from "../services/graph-snapshots.js";
import { postPrComment } from "../services/pr-comment.js";
import { autoGenerateDocsOnPush } from "../services/repo-docs.js";
import { safeEqual } from "../lib/tokens.js";

type WebhookBody = {
  ref: string;
  commit_sha: string;
  event: "push" | "pull_request";
  pr_number?: number;
  pr_title?: string;
  pr_state?: "open" | "closed";
  payload: Record<string, unknown>;
};

/**
 * Producer A for Kubernetes (GP-103): the user's CI renders the pull request head
 * (`helm template`, `kustomize build`, or plain `cat`) and posts the result. We map
 * it, colour it against what main says today, and store it as the PR's snapshot.
 *
 * The base is the repository's **latest documentation snapshot of main** (GP-102),
 * at the time we process this. A repository whose main has no diagram yet — its
 * very first pull request, or a chart whose templates we cannot parse — compares
 * against nothing, so everything reads as created. That is honest, and the snapshot
 * records `base: "none"` so the reader knows which of the two they are looking at.
 *
 * Rendering happens in the user's CI and nowhere else. `helm` and `kustomize` are
 * Go binaries with no credible Node implementation, and shelling out to them would
 * put arbitrary chart code in our runtime — so we ingest what they produced, which
 * is the same posture as ingesting a plan.json instead of running `terraform`.
 */
async function ingestManifests(
  app: FastifyInstance,
  repo: RepositoryRow,
  body: WebhookBody,
  objects: K8sObject[],
): Promise<void> {
  const head = mapK8sObjects(objects);

  // Rendered manifests of **main** are that branch's documentation, not a review
  // of it: they are stored exactly as the repository-parsing producer (GP-102)
  // would have stored them. This is the only way a Helm chart or a kustomize
  // overlay is ever documented — its templates are Go source, so there is nothing
  // in the repository for us to read, and the render its CI already does is the
  // truth. It also gives its pull requests something to be compared against.
  if (body.event === "push") {
    await replaceSnapshot(app, repo.id, "k8s_manifest", null, body.commit_sha);
    await insertGraphSnapshot(app.db, {
      repositoryId: repo.id,
      source: "k8s_manifest",
      ref: repo.defaultBranch,
      commitSha: body.commit_sha,
      prNumber: null,
      graph: head,
      extraStats: { trigger: "auto", rendered: true, objects: objects.length },
    });
    return;
  }

  const [base] = await app.db
    .select()
    .from(graphSnapshots)
    .where(
      and(
        eq(graphSnapshots.repositoryId, repo.id),
        eq(graphSnapshots.source, "k8s_manifest"),
      ),
    )
    .orderBy(desc(graphSnapshots.createdAt))
    .limit(1);

  const prNumber = body.pr_number ?? null;
  await replaceSnapshot(app, repo.id, "k8s_rendered", prNumber, body.commit_sha);

  const snapshot = await insertGraphSnapshot(app.db, {
    repositoryId: repo.id,
    source: "k8s_rendered",
    ref: body.ref,
    commitSha: body.commit_sha,
    prNumber,
    graph: changesFromBase(base?.graph ?? null, head),
    extraStats: {
      base: base?.id ?? "none",
      baseCommitSha: base?.commitSha ?? null,
      objects: objects.length,
    },
  });

  if (snapshot.prNumber !== null) {
    app.runInBackground(postPrComment(app, snapshot));
  }
}

/**
 * Drop the snapshot a re-delivery is about to replace. CI retries, and two
 * diagrams of one commit is not history — it is the same picture, twice.
 */
async function replaceSnapshot(
  app: FastifyInstance,
  repositoryId: string,
  source: "k8s_manifest" | "k8s_rendered",
  prNumber: number | null,
  commitSha: string,
): Promise<void> {
  await app.db
    .delete(graphSnapshots)
    .where(
      and(
        eq(graphSnapshots.repositoryId, repositoryId),
        eq(graphSnapshots.source, source),
        prNumber === null
          ? isNull(graphSnapshots.prNumber)
          : eq(graphSnapshots.prNumber, prNumber),
        eq(graphSnapshots.commitSha, commitSha),
      ),
    );
}

/**
 * Producer A: if the payload is a Terraform plan, parse it into a GraphSnapshot.
 * Wrapped so ingestion never fails on a parse error — the event is flagged with
 * the message instead, and the caller still returns 202.
 */
async function ingestPlan(
  app: FastifyInstance,
  repositoryId: string,
  body: WebhookBody,
  eventId: string,
): Promise<void> {
  if (!isTerraformPlan(body.payload)) return;
  try {
    const graph = parsePlanToGraph(body.payload);
    const snapshot = await insertGraphSnapshot(app.db, {
      repositoryId,
      source: "plan",
      ref: body.ref,
      commitSha: body.commit_sha,
      prNumber: body.pr_number ?? null,
      graph,
    });
    // GP-38: post/update the GitHub PR comment in the background (gated by the
    // per-repo flag inside postPrComment; never blocks or fails ingestion).
    if (snapshot.prNumber !== null) {
      app.runInBackground(postPrComment(app, snapshot));
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    app.log.error({ err, eventId }, "plan parse failed");
    await app.db
      .update(ingestionEvents)
      .set({ parseError: message })
      .where(eq(ingestionEvents.id, eventId));
  }
}

/**
 * Upsert the PullRequest (GP-14) for a pull_request webhook. Title/state are
 * only overwritten when supplied, so a later plan-only webhook for the same PR
 * doesn't wipe metadata sent by an earlier call.
 */
async function upsertPullRequest(
  app: FastifyInstance,
  repositoryId: string,
  body: WebhookBody,
): Promise<void> {
  if (body.event !== "pull_request" || body.pr_number === undefined) return;
  await app.db
    .insert(pullRequests)
    .values({
      repositoryId,
      number: body.pr_number,
      title: body.pr_title ?? null,
      state: body.pr_state ?? "open",
      sourceRef: body.ref,
      latestCommitSha: body.commit_sha,
    })
    .onConflictDoUpdate({
      target: [pullRequests.repositoryId, pullRequests.number],
      set: {
        sourceRef: body.ref,
        latestCommitSha: body.commit_sha,
        updatedAt: new Date(),
        ...(body.pr_title !== undefined ? { title: body.pr_title } : {}),
        ...(body.pr_state !== undefined ? { state: body.pr_state } : {}),
      },
    });
}

const UUID_PATTERN =
  "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$";

/** 10 MB — the largest ingestion payload we accept. */
const MAX_PAYLOAD_BYTES = 10 * 1024 * 1024;

const webhookParamsSchema = {
  type: "object",
  required: ["repositoryId"],
  additionalProperties: false,
  properties: { repositoryId: { type: "string", pattern: UUID_PATTERN } },
};

const webhookBodySchema = {
  type: "object",
  required: ["ref", "commit_sha", "event", "payload"],
  additionalProperties: false,
  properties: {
    ref: { type: "string", minLength: 1, maxLength: 500 },
    commit_sha: { type: "string", minLength: 1, maxLength: 200 },
    event: { type: "string", enum: ["push", "pull_request"] },
    // Present for pull_request events; links a plan snapshot to its PR (GP-13)
    // and identifies the PullRequest to upsert (GP-14). Required below for PRs.
    pr_number: { type: "integer", minimum: 1 },
    pr_title: { type: "string", maxLength: 500 },
    pr_state: { type: "string", enum: ["open", "closed"] },
    // What CI has to say. For a Terraform repository this is the plan.json
    // itself; for a kubernetes one it is `{ manifests: "<rendered YAML>" }`
    // (GP-103). A push carries neither — it only says that main moved.
    payload: { type: "object" },
  },
  // pr_number is mandatory for pull_request events.
  allOf: [
    {
      if: { properties: { event: { const: "pull_request" } } },
      then: { required: ["pr_number"] },
    },
  ],
};

const idParamsSchema = {
  type: "object",
  required: ["id"],
  additionalProperties: false,
  properties: { id: { type: "string", pattern: UUID_PATTERN } },
};

export const ingestionRoutes: FastifyPluginAsync = async (app) => {
  app.post(
    "/webhooks/ci/:repositoryId",
    {
      bodyLimit: MAX_PAYLOAD_BYTES,
      schema: { params: webhookParamsSchema, body: webhookBodySchema },
    },
    async (request, reply) => {
      const { repositoryId } = request.params as { repositoryId: string };
      const body = request.body as WebhookBody;

      const [repo] = await app.db
        .select()
        .from(repositories)
        .where(eq(repositories.id, repositoryId));
      if (!repo) {
        return reply
          .code(404)
          .send({ error: "Not Found", message: "repository not found" });
      }

      const header = request.headers["x-groundplan-token"];
      const provided = Array.isArray(header) ? header[0] : header;
      if (!provided || !safeEqual(provided, repo.webhookToken)) {
        return reply
          .code(401)
          .send({ error: "Unauthorized", message: "invalid webhook token" });
      }

      const kubernetes = repo.iacType === "kubernetes";

      // A pull request is where the two kinds of repository part company: one
      // sends a Terraform plan, the other sends the manifests its CI rendered.
      // Sending the wrong one is a CI misconfiguration, and it is told so now —
      // at the point of failure, where `curl -sf` fails the step somebody is
      // watching — rather than being stored and quietly never drawn.
      let objects: K8sObject[] | null = null;
      const rendered = kubernetes ? body.payload["manifests"] : undefined;
      const sentManifests = typeof rendered === "string" && rendered.trim() !== "";

      // A pull request MUST carry manifests — there is nothing else it could mean.
      // A push MAY: a raw-YAML repository lets us read main ourselves (GP-102),
      // while a chart or an overlay has nothing readable in it and sends the render
      // its CI already did. Both are documentation of main; only the source differs.
      if (kubernetes && (body.event === "pull_request" || sentManifests)) {
        const manifests = rendered;
        if (typeof manifests !== "string" || manifests.trim() === "") {
          return reply.code(422).send({
            error: "Unprocessable Entity",
            message:
              "this repository holds kubernetes manifests — send the rendered YAML as payload.manifests, not a Terraform plan",
          });
        }
        try {
          objects = parseManifestStream(manifests);
        } catch (err) {
          if (err instanceof InvalidManifestError) {
            // Half a rendered stream is not something to store: unlike a repository
            // walk, where one bad file is just a file, the body *is* the payload.
            return reply
              .code(422)
              .send({ error: "Unprocessable Entity", message: err.message });
          }
          throw err;
        }
        if (objects.length === 0) {
          return reply.code(422).send({
            error: "Unprocessable Entity",
            message:
              "the rendered manifests held no Kubernetes objects — check the render step of your CI job",
          });
        }
      }

      const [row] = await app.db
        .insert(ingestionEvents)
        .values({
          repositoryId,
          ref: body.ref,
          commitSha: body.commit_sha,
          event: body.event,
          payload: body.payload,
        })
        .returning({ id: ingestionEvents.id });

      if (objects) await ingestManifests(app, repo, body, objects);
      else if (row && !kubernetes) await ingestPlan(app, repositoryId, body, row.id);
      await upsertPullRequest(app, repositoryId, body);

      // Living docs (GP-23): a push to the default branch regenerates the docs
      // snapshot in the background — the webhook still returns 202 immediately.
      // Unless CI has just handed us main already rendered, in which case reading
      // the repository again would only overwrite the truth with a worse guess.
      if (body.event === "push" && !sentManifests) {
        app.runInBackground(autoGenerateDocsOnPush(app, repositoryId, body));
      }

      return reply.code(202).send({ id: row?.id });
    },
  );

  app.get(
    "/repositories/:id/events",
    { schema: { params: idParamsSchema } },
    async (request, reply) => {
      const { id } = request.params as { id: string };

      const [repo] = await app.db
        .select({ id: repositories.id })
        .from(repositories)
        .where(eq(repositories.id, id));
      if (!repo) {
        return reply
          .code(404)
          .send({ error: "Not Found", message: "repository not found" });
      }

      return app.db
        .select(publicEventColumns)
        .from(ingestionEvents)
        .where(eq(ingestionEvents.repositoryId, id))
        .orderBy(desc(ingestionEvents.receivedAt))
        .limit(20);
    },
  );
};
