import type { FastifyInstance, FastifyPluginAsync } from "fastify";
import { desc, eq } from "drizzle-orm";

import {
  ingestionEvents,
  publicEventColumns,
  pullRequests,
  repositories,
} from "../db/schema.js";
import { isTerraformPlan, parsePlanToGraph } from "../graph/plan-parser.js";
import { insertGraphSnapshot } from "../services/graph-snapshots.js";
import { postPrComment } from "../services/pr-comment.js";
import { autoGenerateDocsOnPush } from "../services/repo-docs.js";
import { safeEqual } from "../lib/tokens.js";

type WebhookBody = {
  ref: string;
  commit_sha: string;
  event: "push" | "pull_request";
  pr_number?: number;
  pr_title?: string;
  pr_state?: "open" | "closed";
  payload: Record<string, unknown>;
};

/**
 * Producer A: if the payload is a Terraform plan, parse it into a GraphSnapshot.
 * Wrapped so ingestion never fails on a parse error — the event is flagged with
 * the message instead, and the caller still returns 202.
 */
async function ingestPlan(
  app: FastifyInstance,
  repositoryId: string,
  body: WebhookBody,
  eventId: string,
): Promise<void> {
  if (!isTerraformPlan(body.payload)) return;
  try {
    const graph = parsePlanToGraph(body.payload);
    const snapshot = await insertGraphSnapshot(app.db, {
      repositoryId,
      source: "plan",
      ref: body.ref,
      commitSha: body.commit_sha,
      prNumber: body.pr_number ?? null,
      graph,
    });
    // GP-38: post/update the GitHub PR comment in the background (gated by the
    // per-repo flag inside postPrComment; never blocks or fails ingestion).
    if (snapshot.prNumber !== null) {
      app.runInBackground(postPrComment(app, snapshot));
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    app.log.error({ err, eventId }, "plan parse failed");
    await app.db
      .update(ingestionEvents)
      .set({ parseError: message })
      .where(eq(ingestionEvents.id, eventId));
  }
}

/**
 * Upsert the PullRequest (GP-14) for a pull_request webhook. Title/state are
 * only overwritten when supplied, so a later plan-only webhook for the same PR
 * doesn't wipe metadata sent by an earlier call.
 */
async function upsertPullRequest(
  app: FastifyInstance,
  repositoryId: string,
  body: WebhookBody,
): Promise<void> {
  if (body.event !== "pull_request" || body.pr_number === undefined) return;
  await app.db
    .insert(pullRequests)
    .values({
      repositoryId,
      number: body.pr_number,
      title: body.pr_title ?? null,
      state: body.pr_state ?? "open",
      sourceRef: body.ref,
      latestCommitSha: body.commit_sha,
    })
    .onConflictDoUpdate({
      target: [pullRequests.repositoryId, pullRequests.number],
      set: {
        sourceRef: body.ref,
        latestCommitSha: body.commit_sha,
        updatedAt: new Date(),
        ...(body.pr_title !== undefined ? { title: body.pr_title } : {}),
        ...(body.pr_state !== undefined ? { state: body.pr_state } : {}),
      },
    });
}

const UUID_PATTERN =
  "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$";

/** 10 MB — the largest ingestion payload we accept. */
const MAX_PAYLOAD_BYTES = 10 * 1024 * 1024;

const webhookParamsSchema = {
  type: "object",
  required: ["repositoryId"],
  additionalProperties: false,
  properties: { repositoryId: { type: "string", pattern: UUID_PATTERN } },
};

const webhookBodySchema = {
  type: "object",
  required: ["ref", "commit_sha", "event", "payload"],
  additionalProperties: false,
  properties: {
    ref: { type: "string", minLength: 1, maxLength: 500 },
    commit_sha: { type: "string", minLength: 1, maxLength: 200 },
    event: { type: "string", enum: ["push", "pull_request"] },
    // Present for pull_request events; links a plan snapshot to its PR (GP-13)
    // and identifies the PullRequest to upsert (GP-14). Required below for PRs.
    pr_number: { type: "integer", minimum: 1 },
    pr_title: { type: "string", maxLength: 500 },
    pr_state: { type: "string", enum: ["open", "closed"] },
    payload: { type: "object" },
  },
  // pr_number is mandatory for pull_request events.
  allOf: [
    {
      if: { properties: { event: { const: "pull_request" } } },
      then: { required: ["pr_number"] },
    },
  ],
};

const idParamsSchema = {
  type: "object",
  required: ["id"],
  additionalProperties: false,
  properties: { id: { type: "string", pattern: UUID_PATTERN } },
};

export const ingestionRoutes: FastifyPluginAsync = async (app) => {
  app.post(
    "/webhooks/ci/:repositoryId",
    {
      bodyLimit: MAX_PAYLOAD_BYTES,
      schema: { params: webhookParamsSchema, body: webhookBodySchema },
    },
    async (request, reply) => {
      const { repositoryId } = request.params as { repositoryId: string };
      const body = request.body as WebhookBody;

      const [repo] = await app.db
        .select({
          id: repositories.id,
          iacType: repositories.iacType,
          webhookToken: repositories.webhookToken,
        })
        .from(repositories)
        .where(eq(repositories.id, repositoryId));
      if (!repo) {
        return reply
          .code(404)
          .send({ error: "Not Found", message: "repository not found" });
      }

      const header = request.headers["x-groundplan-token"];
      const provided = Array.isArray(header) ? header[0] : header;
      if (!provided || !safeEqual(provided, repo.webhookToken)) {
        return reply
          .code(401)
          .send({ error: "Unauthorized", message: "invalid webhook token" });
      }

      // A push says main moved, which is true of both kinds of repository — the
      // docs producer downstream knows which one to run (GP-102). A pull request,
      // though, carries a Terraform plan, and a kubernetes repository has none to
      // send: it is refused rather than left to accumulate events nothing reads.
      // (GP-103 gives it a payload of its own and this becomes a branch.)
      if (repo.iacType !== "terraform" && body.event !== "push") {
        return reply.code(422).send({
          error: "Unprocessable Entity",
          message:
            "this repository holds kubernetes manifests — send rendered manifests, not a Terraform plan",
        });
      }

      const [row] = await app.db
        .insert(ingestionEvents)
        .values({
          repositoryId,
          ref: body.ref,
          commitSha: body.commit_sha,
          event: body.event,
          payload: body.payload,
        })
        .returning({ id: ingestionEvents.id });

      if (row) await ingestPlan(app, repositoryId, body, row.id);
      await upsertPullRequest(app, repositoryId, body);

      // Living docs (GP-23): a push to the default branch regenerates the docs
      // snapshot in the background — the webhook still returns 202 immediately.
      if (body.event === "push") {
        app.runInBackground(autoGenerateDocsOnPush(app, repositoryId, body));
      }

      return reply.code(202).send({ id: row?.id });
    },
  );

  app.get(
    "/repositories/:id/events",
    { schema: { params: idParamsSchema } },
    async (request, reply) => {
      const { id } = request.params as { id: string };

      const [repo] = await app.db
        .select({ id: repositories.id })
        .from(repositories)
        .where(eq(repositories.id, id));
      if (!repo) {
        return reply
          .code(404)
          .send({ error: "Not Found", message: "repository not found" });
      }

      return app.db
        .select(publicEventColumns)
        .from(ingestionEvents)
        .where(eq(ingestionEvents.repositoryId, id))
        .orderBy(desc(ingestionEvents.receivedAt))
        .limit(20);
    },
  );
};
