import { test, before, after } from "node:test";
import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import type { FastifyInstance } from "fastify";
import { eq } from "drizzle-orm";

import { buildApp } from "../app.js";
import { seedOrg } from "../test-support.js";
import { loadEnv } from "../config/env.js";
import { runMigrations } from "../db/migrate.js";
import { repositories, type RepositoryRow } from "../db/schema.js";
import { generateDocsSnapshot, autoGenerateDocsOnPush } from "./repo-docs.js";

const env = loadEnv();
const exec = promisify(execFile);

let fixtureDir: string;
let fixtureUrl: string;

function bucket(name: string): string {
  return `resource "aws_s3_bucket" "${name}" {\n  bucket = "${name}"\n}\n`;
}

/** Commit `main.tf` with the given bucket resource names; return the new sha. */
async function writeFixture(names: string[]): Promise<string> {
  const git = (args: string[]) => exec("git", args, { cwd: fixtureDir });
  await fs.writeFile(
    path.join(fixtureDir, "main.tf"),
    names.map(bucket).join("\n"),
  );
  await git(["add", "."]);
  // --allow-empty: re-writing the same resource set (to reset state between the
  // rename steps) still advances HEAD so the next clone sees a fresh tip.
  await git(["commit", "--allow-empty", "-m", `resources: ${names.join(",")}`]);
  return (await git(["rev-parse", "HEAD"])).stdout.trim();
}

before(async () => {
  await runMigrations(env.databaseUrl);
  fixtureDir = await fs.mkdtemp(path.join(os.tmpdir(), "gp-recon-"));
  const git = (args: string[]) => exec("git", args, { cwd: fixtureDir });
  await git(["init", "-b", "main"]);
  await git(["config", "user.email", "t@example.com"]);
  await git(["config", "user.name", "Fixture"]);
  await writeFixture(["data", "stable"]);
  fixtureUrl = `file://${fixtureDir}`;
});

after(async () => {
  await fs.rm(fixtureDir, { recursive: true, force: true });
});

let counter = 0;
async function createRepo(
  app: FastifyInstance,
  orgId: string,
): Promise<{ projectId: string; repo: RepositoryRow }> {
  counter += 1;
  const p = await app.inject({
    method: "POST",
    url: `/api/v1/orgs/${orgId}/projects`,
    payload: { name: "R", slug: `recon-${Date.now()}-${counter}` },
  });
  const projectId = p.json().id;
  const r = await app.inject({
    method: "POST",
    url: `/api/v1/orgs/${orgId}/projects/${projectId}/repositories`,
    payload: { provider: "github", url: fixtureUrl, defaultBranch: "main" },
  });
  const [repo] = await app.db
    .select()
    .from(repositories)
    .where(eq(repositories.id, r.json().id));
  return { projectId, repo: repo as RepositoryRow };
}

async function note(
  app: FastifyInstance,
  orgId: string,
  repoId: string,
  anchor: string,
): Promise<string> {
  const res = await app.inject({
    method: "POST",
    url: `/api/v1/orgs/${orgId}/repositories/${repoId}/annotations`,
    payload: { type: "note", anchors: [anchor], body: `about ${anchor}` },
  });
  return res.json().id;
}

async function getAnnotation(app: FastifyInstance, orgId: string, id: string) {
  const res = await app.inject({
    method: "GET",
    url: `/api/v1/orgs/${orgId}/annotations/${id}`,
  });
  return res.json();
}

test("docs generation reconciles: rename orphans, re-add re-resolves; others untouched", async () => {
  const app = await buildApp(env);
  const orgId = await seedOrg(app);
  try {
    await writeFixture(["data", "stable"]);
    const { projectId, repo } = await createRepo(app, orgId);
    const onData = await note(app, orgId, repo.id, "aws_s3_bucket.data");
    const onStable = await note(app, orgId, repo.id, "aws_s3_bucket.stable");

    // First (manual) generation — everything present, so both resolve.
    await generateDocsSnapshot(app, repo);
    assert.equal((await getAnnotation(app, orgId, onData)).status, "resolved");
    assert.equal((await getAnnotation(app, orgId, onStable)).status, "resolved");

    // Rename `data` -> `renamed` and regenerate: the note on `data` orphans and
    // records the missing address; the note on `stable` stays resolved.
    await writeFixture(["renamed", "stable"]);
    await generateDocsSnapshot(app, repo);
    const orphaned = await getAnnotation(app, orgId, onData);
    assert.equal(orphaned.status, "orphaned");
    assert.deepEqual(orphaned.missingAnchors, ["aws_s3_bucket.data"]);
    assert.equal((await getAnnotation(app, orgId, onStable)).status, "resolved");

    // Re-add the resource with the same address and regenerate: it returns to
    // resolved with no manual action, and missingAnchors clears.
    await writeFixture(["data", "stable"]);
    await generateDocsSnapshot(app, repo);
    const healed = await getAnnotation(app, orgId, onData);
    assert.equal(healed.status, "resolved");
    assert.deepEqual(healed.missingAnchors, []);

    await app.inject({ method: "DELETE", url: `/api/v1/orgs/${orgId}/projects/${projectId}` });
  } finally {
    await app.close();
  }
});

test("the on-merge/push path also reconciles annotations", async () => {
  const app = await buildApp(env);
  const orgId = await seedOrg(app);
  try {
    await writeFixture(["data", "stable"]);
    const { projectId, repo } = await createRepo(app, orgId);
    const onData = await note(app, orgId, repo.id, "aws_s3_bucket.data");

    const sha = await writeFixture(["renamed", "stable"]);
    await autoGenerateDocsOnPush(app, repo.id, {
      ref: "refs/heads/main",
      commit_sha: sha,
      event: "push",
    });

    assert.equal((await getAnnotation(app, orgId, onData)).status, "orphaned");

    await app.inject({ method: "DELETE", url: `/api/v1/orgs/${orgId}/projects/${projectId}` });
  } finally {
    await app.close();
  }
});
