import type { FastifyInstance } from "fastify";
import { and, eq } from "drizzle-orm";

import {
  graphSnapshots,
  repositories,
  type GraphSnapshotRow,
  type RepositoryRow,
} from "../db/schema.js";
import { parseHclRepo } from "../graph/hcl-parser.js";
import { reconcileRepositoryAnnotations } from "./annotation-reconcile.js";
import { insertGraphSnapshot } from "./graph-snapshots.js";
import { readRepoTextFiles } from "./repo-files.js";

/** Thrown when a docs generation is already running for a repository. */
export class DocsGenerationInProgressError extends Error {
  constructor() {
    super("documentation generation already in progress for this repository");
    this.name = "DocsGenerationInProgressError";
  }
}

/** How a docs snapshot was produced (GP-23 / GP-26 timeline badge). */
export type DocsTrigger = "manual" | "auto";

export type GenerateDocsOptions = {
  /** Check out this exact commit instead of the branch tip (auto-docs). */
  commitSha?: string;
  /** Recorded in stats.trigger for the docs history timeline. */
  trigger?: DocsTrigger;
};

// Per-repo in-memory lock: one docs generation at a time. Acquired synchronously
// (before the first await) so two overlapping calls can't both pass the guard.
const generating = new Set<string>();

/**
 * Producer B (GP-15): clone the repo's default branch, statically parse its
 * Terraform, and store a `source=hcl` GraphSnapshot. Synchronous for now (no
 * queue); the clone is always cleaned up by `readRepoTextFiles`.
 */
export async function generateDocsSnapshot(
  app: FastifyInstance,
  repo: RepositoryRow,
  opts: GenerateDocsOptions = {},
): Promise<GraphSnapshotRow> {
  if (generating.has(repo.id)) throw new DocsGenerationInProgressError();
  generating.add(repo.id);
  try {
    let accessToken: string | null = null;
    if (repo.accessToken) {
      try {
        accessToken = app.encryptor.decrypt(repo.accessToken);
      } catch (err) {
        app.log.warn({ err, repositoryId: repo.id }, "could not decrypt stored PAT");
      }
    }

    const { files, headSha } = await readRepoTextFiles(
      { url: repo.url, provider: repo.provider, ref: repo.defaultBranch, accessToken },
      (path) => path.endsWith(".tf"),
      opts.commitSha,
    );

    const { graph, warnings } = parseHclRepo(files);

    const snapshot = await insertGraphSnapshot(app.db, {
      repositoryId: repo.id,
      source: "hcl",
      ref: repo.defaultBranch,
      commitSha: headSha,
      prNumber: null,
      graph,
      extraStats: { warnings, trigger: opts.trigger ?? "manual" },
    });

    // Reconcile the annotation layer against the new snapshot (ADR #4 / GP-57):
    // a deterministic, synchronous post-step, so every docs generation (manual,
    // regenerate, on-merge) keeps annotation status in sync with the graph.
    await reconcileRepositoryAnnotations(app.db, repo.id, graph);

    return snapshot;
  } finally {
    generating.delete(repo.id);
  }
}

/** Does a webhook `ref` point at the repository's default branch? */
function isDefaultBranch(ref: string, defaultBranch: string): boolean {
  return ref === defaultBranch || ref === `refs/heads/${defaultBranch}`;
}

type PushBody = { ref: string; commit_sha: string; event: string };

/**
 * Living docs (GP-23): a push to the default branch regenerates the docs
 * snapshot for the pushed commit. Idempotent (skips if a snapshot for that sha
 * already exists) and non-fatal (a locked generation is skipped and logged).
 * Intended to run in the background after the webhook 202.
 */
export async function autoGenerateDocsOnPush(
  app: FastifyInstance,
  repositoryId: string,
  body: PushBody,
): Promise<void> {
  if (body.event !== "push") return;

  const [repo] = await app.db
    .select()
    .from(repositories)
    .where(eq(repositories.id, repositoryId));
  if (!repo || !isDefaultBranch(body.ref, repo.defaultBranch)) return;

  const [existing] = await app.db
    .select({ id: graphSnapshots.id })
    .from(graphSnapshots)
    .where(
      and(
        eq(graphSnapshots.repositoryId, repositoryId),
        eq(graphSnapshots.source, "hcl"),
        eq(graphSnapshots.commitSha, body.commit_sha),
      ),
    )
    .limit(1);
  if (existing) {
    app.log.info(
      { repositoryId, commitSha: body.commit_sha },
      "docs snapshot already exists for this sha, skipping auto-generation",
    );
    return;
  }

  try {
    await generateDocsSnapshot(app, repo, {
      commitSha: body.commit_sha,
      trigger: "auto",
    });
  } catch (err) {
    if (err instanceof DocsGenerationInProgressError) {
      app.log.info(
        { repositoryId },
        "docs generation already running, skipping (next push will regenerate)",
      );
    } else {
      app.log.error({ err, repositoryId }, "auto docs generation failed");
    }
  }
}
